# Generated by Django 5.1.1 on 2024-10-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='pssword',
            new_name='password',
        ),
    ]
