# Generated by Django 5.1.1 on 2024-10-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_registeruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
